// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb43GlzYN_K3Jj1K5_eYz6psdLMhmUWWo',
    appId: '1:435386596423:web:622433c1c6356b7c300562',
    messagingSenderId: '435386596423',
    projectId: 'triplink2',
    authDomain: 'triplink2.firebaseapp.com',
    storageBucket: 'triplink2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4lFNwBVw1CNYEnNH00852TXHjz8C7D7Q',
    appId: '1:435386596423:android:29118d11c2b8294c300562',
    messagingSenderId: '435386596423',
    projectId: 'triplink2',
    storageBucket: 'triplink2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj_9pevZZDRytyt4J4-ncQ9pXZtUizWow',
    appId: '1:435386596423:ios:9a7cb91d0d108d68300562',
    messagingSenderId: '435386596423',
    projectId: 'triplink2',
    storageBucket: 'triplink2.firebasestorage.app',
    iosBundleId: 'com.example.triplink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj_9pevZZDRytyt4J4-ncQ9pXZtUizWow',
    appId: '1:435386596423:ios:9a7cb91d0d108d68300562',
    messagingSenderId: '435386596423',
    projectId: 'triplink2',
    storageBucket: 'triplink2.firebasestorage.app',
    iosBundleId: 'com.example.triplink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn4zfjPP4ZOZWARjawztac38NG7O4kdIg',
    appId: '1:435386596423:web:5c62432b53a2d06d300562',
    messagingSenderId: '435386596423',
    projectId: 'triplink2',
    authDomain: 'triplink2.firebaseapp.com',
    storageBucket: 'triplink2.firebasestorage.app',
  );

}